FROM tiangolo/uwsgi-nginx-flask:python3.8-alpine
RUN pip install requests


ENV LISTEN_PORT 10003
EXPOSE 10003


ENV IS_LOCAL=0
RUN if [ "$IS_LOCAL" -ne 0 ] ; then VOLUME /app fi


VOLUME /app 


COPY ./app /app
RUN rm -f /app/users/.gitkeep
