FROM tiangolo/uwsgi-nginx-flask:python3.8-alpine
RUN pip install requests


ENV LISTEN_PORT 10003
EXPOSE 10003

ARG islocal=0
RUN if [ "x$islocal" = 0 ] ; then VOLUME /app ; fi


COPY ./app /app
RUN rm -f /app/users/.gitkeep
